"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================
# 🔐 Security Settings
# ==============================
# استخدام environment variable للـ SECRET_KEY مع قيمة احتياطية للتطوير فقط
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY', 
    'django-insecure-kflkrqn57mhd^n&qy74z7+ctkqik2-*+7t5&g$rl6s9r4@g4+g'
)

# يجب تعطيل DEBUG في بيئة الإنتاج
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")


# ==============================
# 🧩 Installed Apps
# ==============================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # APIs و Third-party packages
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',  # ✅ تفعيل CORS headers

    # Project apps
    'users',
    "warehouses.apps.WarehousesConfig",
    'book_requests',
    'books',
    'schools',
    'school_requests',
    'notifications',
    
]

# ==============================
# 👤 Custom User
# ==============================
AUTH_USER_MODEL = 'users.User'

# ==============================
# 🎨 Templates
# ==============================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # مسار مجلد القوالب العام
        'APP_DIRS': True,  # للبحث عن القوالب داخل مجلدات التطبيقات
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ==============================
# ⚙️ REST Framework & JWT
# ==============================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # JWT (للتعامل مع التوكنز)
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # Session (للتجارب والإدارة)
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        # مؤقتًا مفتوح أثناء التطوير
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # ⚡ Rate Limiting (Throttling)
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",  # للمستخدمين غير المسجلين
        "user": "1000/hour",  # للمستخدمين المسجلين
        "uploads": "20/hour",  # لرفع الملفات
        "reports": "50/hour",  # للتقارير
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=6),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}





# ==============================
# 🧱 Middleware
# ==============================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ✅ يجب أن يكون في الأول بعد SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ==============================
# 🌐 URLs & WSGI
# ==============================
ROOT_URLCONF = 'core.urls'
WSGI_APPLICATION = 'core.wsgi.application'


# ==============================
# 🗄️ Database
# ==============================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "pgsql"),
        "USER": os.getenv("POSTGRES_USER", "pgsql"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "pgsql"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),   # localhost for local development
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": 60,
    }
}


# ==============================
# ⚡ Redis Cache Configuration
# ==============================
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://localhost:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "retry_on_timeout": True
            },
        },
        "KEY_PREFIX": "ketabi",
        "TIMEOUT": 300,  # 5 minutes default
    }
}

# استخدام Redis للـ sessions (optional - أفضل للأداء)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# ==============================
# 🔐 Password Validation
# ==============================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ==============================
# 🌍 Internationalization
# ==============================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==============================
# 🖼️ Static & Media Files
# ==============================
STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = '/app/data/media'


# ==============================
# ⚙️ Other Settings
# ==============================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================
# 🌐 CORS Settings
# ==============================
# في التطوير: السماح لجميع المصادر
# في الإنتاج: تحديد المصادر المسموحة
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # في الإنتاج، حدد النطاقات المسموحة
    CORS_ALLOWED_ORIGINS = os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001'
    ).split(',')

# السماح بإرسال Cookies والـ credentials
CORS_ALLOW_CREDENTIALS = True

# CSRF Settings
CSRF_TRUSTED_ORIGINS = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000'
).split(',')

# Prevent Django from redirecting POST requests to slash-terminated URLs
# Some clients (mobile/web apps) post to endpoints without trailing slash.
APPEND_SLASH = False

# Add common local web debug ports to trusted origins for CSRF (useful for Flutter web)
additional_csrf_origins = [
    'http://localhost:53995',
    'http://127.0.0.1:53995',
    'http://192.168.105.69:53995',
]
for origin in additional_csrf_origins:
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# ==============================
# 📋 Celery Settings
# ==============================
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://redis:6379/0')

# ==============================
# 📊 Logging Configuration
# ==============================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'errors.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_errors'],
            'level': 'INFO',
        },
        'warehouses': {
            'handlers': ['console', 'file_errors'],
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
        'notifications': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# إنشاء مجلد logs
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)


# Firebase
FIREBASE_CREDENTIALS_PATH = os.getenv('FIREBASE_CREDENTIALS_PATH', None)
