# Generated by Django 5.1 on 2026-01-09 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('book_request_created', 'طلب كتب جديد'), ('book_request_approved', 'اعتماد طلب كتب'), ('book_request_rejected', 'رفض طلب كتب'), ('school_request_created', 'طلب مدرسة جديد'), ('school_request_approved', 'اعتماد طلب مدرسة'), ('school_request_rejected', 'رفض طلب مدرسة'), ('shipment_created', 'شحنة جديدة'), ('shipment_assigned', 'تم إسناد شحنة'), ('shipment_out_for_delivery', 'شحنة قيد التوصيل'), ('shipment_delivered', 'تم توصيل شحنة'), ('shipment_confirmed', 'تأكيد استلام شحنة'), ('low_stock_alert', 'تنبيه مخزون منخفض'), ('stock_updated', 'تحديث المخزون'), ('general', 'إشعار عام'), ('urgent', 'إشعار عاجل')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx'),
        ),
    ]
