# Generated by Django 5.1 on 2025-11-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_devicetoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicetoken',
            new_name='notificatio_user_id_f0e72c_idx',
            old_name='notif_user_active_idx',
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='device_token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
