version: '3.9'

services:
  db:
    image: postgres:16
    container_name: ketabi_db
    restart: always
    env_file: .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: ketabi_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: ketabi_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery_worker:
    build: ./backend
    container_name: ketabi_celery_worker
    command: celery -A core.celery worker -l info
    env_file: .env
    depends_on:
      - backend
      - redis

  celery_beat:
    build: ./backend
    container_name: ketabi_celery_beat
    command: celery -A core.celery beat -l info
    env_file: .env
    depends_on:
      - backend
      - redis

  frontend:
    build: ./frontend
    container_name: ketabi_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

  minio:
    image: minio/minio
    container_name: ketabi_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
