# Generated by Django 5.1 on 2025-11-05 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('public', 'حكومية'), ('private', 'خاصة')], default='public', max_length=20)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.province')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='schools_sch_name_5d0cfd_idx'), models.Index(fields=['province', 'type'], name='schools_sch_provinc_7c5876_idx')],
            },
        ),
    ]
