# Generated by Django 5.1 on 2025-12-23 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المديرية')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز المديرية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorates', to='schools.province', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'مديرية',
                'verbose_name_plural': 'المديريات',
                'ordering': ['province', 'name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('public', 'حكومية'), ('private', 'خاصة')], default='public', max_length=20)),
                ('directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.directorate', verbose_name='المديرية')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.province')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='directorate',
            index=models.Index(fields=['province', 'name'], name='schools_dir_provinc_900946_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='directorate',
            unique_together={('province', 'name')},
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='schools_sch_name_5d0cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['province', 'type'], name='schools_sch_provinc_7c5876_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['directorate'], name='schools_sch_directo_58d257_idx'),
        ),
    ]
