# Generated by Django 5.1 on 2025-12-17 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المديرية')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز المديرية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directorates', to='schools.province', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'مديرية',
                'verbose_name_plural': 'المديريات',
                'ordering': ['province', 'name'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.directorate', verbose_name='المديرية'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['directorate'], name='schools_sch_directo_58d257_idx'),
        ),
        migrations.AddIndex(
            model_name='directorate',
            index=models.Index(fields=['province', 'name'], name='schools_dir_provinc_900946_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='directorate',
            unique_together={('province', 'name')},
        ),
    ]
