# Generated by Django 5.1 on 2025-12-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('fulfilled', 'تم التنفيذ')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'طلب كتب',
                'verbose_name_plural': 'طلبات الكتب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='المادة')),
                ('grade', models.CharField(max_length=50, verbose_name='الصف')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('approved_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلبات',
            },
        ),
    ]
