# Generated by Django 5.1 on 2026-01-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequestitem',
            name='term',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='الفصل'),
        ),
    ]
