# Generated by Django 5.1 on 2025-11-18 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_requests', '0002_initial'),
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب كتب', 'verbose_name_plural': 'طلبات الكتب'},
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='reason_rejected',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='subject',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='request_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ministry_admin', 'ministry_staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_requests_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('fulfilled', 'تم التنفيذ')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['province_admin', 'province_staff']}, on_delete=django.db.models.deletion.CASCADE, related_name='book_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='المادة')),
                ('grade', models.CharField(max_length=50, verbose_name='الصف')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('approved_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='book_requests.bookrequest')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلبات',
            },
        ),
    ]
