# Generated by Django 5.1 on 2025-11-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم للوزارة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل التسليم')], default='draft', max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('reason_rejected', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
