# Generated by Django 5.1 on 2025-11-05 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrequest',
            old_name='reason',
            new_name='reason_rejected',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='province',
        ),
        migrations.RemoveField(
            model_name='bookrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ministry_staff', 'ministry_warehouse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='created_by',
            field=models.ForeignKey(default=1, limit_choices_to={'role__in': ['province_staff', 'province_warehouse']}, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='stage',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم للوزارة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل التسليم')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
