# Generated by Django 5.1 on 2025-11-10 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ministry_staff', 'ministry_warehouse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['province_staff', 'province_warehouse']}, on_delete=django.db.models.deletion.CASCADE, related_name='requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
