# Generated by Django 5.1 on 2025-12-23 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_requests', '0001_initial'),
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('staff', models.ManyToManyField(blank=True, related_name='ministry_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('staff', models.ManyToManyField(blank=True, related_name='province_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, db_index=True, help_text='كود التتبع الفريد', max_length=50, null=True)),
                ('to_school_name', models.CharField(blank=True, default='', max_length=255)),
                ('books', models.JSONField()),
                ('courier_role', models.CharField(choices=[('ministry_courier', 'مندوب الوزارة → المحافظة'), ('province_courier', 'مندوب المحافظة → المدرسة')], max_length=32)),
                ('qr_code', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'قيد الإنشاء'), ('assigned', 'مُسندة لمندوب'), ('out_for_delivery', 'خارجة للتسليم'), ('delivered', 'تم التسليم'), ('confirmed', 'مؤكدة (يتم خصم المخزون)'), ('canceled', 'ملغاة')], default='pending', max_length=20)),
                ('current_latitude', models.FloatField(blank=True, help_text='موقع المندوب الحالي - خط العرض', null=True)),
                ('current_longitude', models.FloatField(blank=True, help_text='موقع المندوب الحالي - خط الطول', null=True)),
                ('last_location_update', models.DateTimeField(blank=True, help_text='آخر تحديث للموقع', null=True)),
                ('proof_photo', models.ImageField(blank=True, help_text='صورة إثبات التسليم', null=True, upload_to='shipments/proof/')),
                ('digital_signature', models.ImageField(blank=True, help_text='التوقيع الرقمي', null=True, upload_to='shipments/signatures/')),
                ('recipient_name', models.CharField(blank=True, default='', help_text='اسم المستلم', max_length=255)),
                ('delivery_notes', models.TextField(blank=True, default='', help_text='ملاحظات التسليم')),
                ('driver_location', models.JSONField(blank=True, help_text='Driver location data', null=True)),
                ('delivery_photos', models.JSONField(blank=True, default=list, help_text='List of delivery photo paths')),
                ('signature_path', models.CharField(blank=True, help_text='Path to signature file', max_length=500)),
                ('signature_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_notes', models.TextField(blank=True, default='', help_text='School receiver notes')),
                ('delivery_condition', models.CharField(blank=True, default='good', help_text='good/damaged', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When school confirmed receipt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_delivery_at', models.DateTimeField(blank=True, help_text='وقت بدء التوصيل', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='وقت التسليم الفعلي', null=True)),
                ('assigned_courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='School staff who confirmed receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_shipments', to=settings.AUTH_USER_MODEL)),
                ('from_ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_out', to='warehouses.ministrywarehouse')),
                ('related_request', models.ForeignKey(blank=True, help_text='Optional link to the originating book request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_from_request', to='book_requests.bookrequest')),
                ('to_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_in', to='warehouses.provincewarehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('first', 'الترم الأول'), ('second', 'الترم الثاني')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('min_threshold', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='books.book')),
                ('ministry_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouses.ministrywarehouse')),
                ('province_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouses.provincewarehouse')),
            ],
            options={
                'unique_together': {('ministry_warehouse', 'book', 'term'), ('province_warehouse', 'book', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'إدخال'), ('out', 'إخراج'), ('adjust', 'تعديل'), ('transfer', 'تحويل')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('previous_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.shipment')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouses.warehousestock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
