# Generated by Django 5.1 on 2025-11-10 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('staff', models.ManyToManyField(related_name='ministry_warehouses_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_warehouses', to='schools.province')),
                ('staff', models.ManyToManyField(related_name='province_warehouses_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('ministry_to_province', 'من الوزارة للمحافظة'), ('province_to_school', 'من المحافظة للمدرسة')], max_length=30)),
                ('books_data', models.JSONField(default=dict, verbose_name='الكتب')),
                ('total_books', models.PositiveIntegerField(default=0)),
                ('qr_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('preparing', 'قيد التجهيز'), ('assigned_to_driver', 'مسندة للمندوب'), ('in_transit', 'قيد النقل'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغاة')], default='preparing', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ministry_driver', 'province_driver']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_shipments', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministry_shipments', to='warehouses.ministrywarehouse')),
                ('to_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_shipments', to='schools.school')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_shipments', to='warehouses.provincewarehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('min_stock_level', models.PositiveIntegerField(default=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory', to='warehouses.provincewarehouse')),
            ],
            options={
                'verbose_name': 'مخزون المستودع',
                'verbose_name_plural': 'مخزونات المستودعات',
                'unique_together': {('warehouse', 'book')},
            },
        ),
    ]
