# Generated by Django 5.1 on 2025-12-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='qr_code_image',
            field=models.TextField(blank=True, help_text='صورة QR Code بصيغة base64', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية الـ QR Code', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='qr_scanned_at',
            field=models.DateTimeField(blank=True, help_text='وقت مسح الـ QR Code', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='qr_token',
            field=models.CharField(blank=True, help_text='رمز فريد للـ QR Code', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='qr_used',
            field=models.BooleanField(default=False, help_text='هل تم استخدام الـ QR Code للتأكيد'),
        ),
    ]
