# Generated by Django 5.1 on 2025-11-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_latitude',
            field=models.FloatField(blank=True, help_text='موقع المندوب الحالي - خط العرض', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_longitude',
            field=models.FloatField(blank=True, help_text='موقع المندوب الحالي - خط الطول', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='وقت التسليم الفعلي', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_notes',
            field=models.TextField(blank=True, default='', help_text='ملاحظات التسليم'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='digital_signature',
            field=models.ImageField(blank=True, help_text='التوقيع الرقمي', null=True, upload_to='shipments/signatures/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='آخر تحديث للموقع', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='proof_photo',
            field=models.ImageField(blank=True, help_text='صورة إثبات التسليم', null=True, upload_to='shipments/proof/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient_name',
            field=models.CharField(blank=True, default='', help_text='اسم المستلم', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='started_delivery_at',
            field=models.DateTimeField(blank=True, help_text='وقت بدء التوصيل', null=True),
        ),
    ]
