# Generated by Django 5.1 on 2025-11-19 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_shipment_current_latitude_shipment_current_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When school confirmed receipt', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='School staff who confirmed receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_condition',
            field=models.CharField(blank=True, default='good', help_text='good/damaged', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_photos',
            field=models.JSONField(blank=True, default=list, help_text='List of delivery photo paths'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_location',
            field=models.JSONField(blank=True, help_text='Driver location data', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_notes',
            field=models.TextField(blank=True, default='', help_text='School receiver notes'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='signature_path',
            field=models.CharField(blank=True, help_text='Path to signature file', max_length=500),
        ),
        migrations.AddField(
            model_name='shipment',
            name='signature_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, help_text='كود التتبع الفريد', max_length=50, null=True),
        ),
    ]
