# Generated by Django 5.1 on 2025-12-28 19:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_add_related_school_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(choices=[('inventory', 'تقرير جرد'), ('stock_count', 'عد المخزون'), ('shipment_log', 'سجل الشحنات'), ('delivery_log', 'سجل التسليمات'), ('warehouse_inspection', 'معاينة المخزن'), ('damage_report', 'تقرير أضرار'), ('maintenance', 'صيانة'), ('other', 'أخرى')], max_length=50, verbose_name='نوع التقرير')),
                ('description', models.TextField(blank=True, verbose_name='وصف التقرير')),
                ('file', models.FileField(upload_to='uploaded_reports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls', 'docx', 'doc', 'csv'])], verbose_name='ملف التقرير')),
                ('file_size', models.IntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('report_date', models.DateField(verbose_name='تاريخ التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('ministry_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to='warehouses.ministrywarehouse', verbose_name='مخزن الوزارة')),
                ('province_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to='warehouses.provincewarehouse', verbose_name='مخزن المحافظة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL, verbose_name='الرافع')),
            ],
            options={
                'verbose_name': 'تقرير مرفوع',
                'verbose_name_plural': 'التقارير المرفوعة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='warehouses.uploadedreport', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='uploadedreport',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='warehouses__uploade_6a33b0_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedreport',
            index=models.Index(fields=['status', '-created_at'], name='warehouses__status_1175ae_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedreport',
            index=models.Index(fields=['report_type', '-created_at'], name='warehouses__report__50f2dd_idx'),
        ),
    ]
