# Generated by Django 5.1 on 2025-11-25 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_requests', '0003_alter_bookrequest_options_and_more'),
        ('warehouses', '0003_shipment_confirmed_at_shipment_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='related_request',
            field=models.ForeignKey(blank=True, help_text='Optional link to the originating book request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_from_request', to='book_requests.bookrequest'),
        ),
    ]
