# Generated by Django 5.1 on 2026-01-09 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('warehouses', '0004_uploadedreport_reportcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(choices=[('ministry_statistics', 'إحصائيات الوزارة'), ('province_statistics', 'إحصائيات المحافظة'), ('warehouse_stock', 'مخزون المستودعات'), ('shipments', 'تقرير الشحنات'), ('books_distribution', 'توزيع الكتب'), ('schools_status', 'حالة المدارس'), ('custom', 'تقرير مخصص')], max_length=50, verbose_name='نوع التقرير')),
                ('scope', models.CharField(choices=[('ministry', 'وزارة'), ('province', 'محافظة')], max_length=20, verbose_name='النطاق')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file', models.FileField(upload_to='reports/%Y/%m/', verbose_name='ملف التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('file_size', models.IntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='عدد التحميلات')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='schools.province', verbose_name='المحافظة')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_reports', to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'scope'], name='warehouses__report__442a34_idx'), models.Index(fields=['created_at'], name='warehouses__created_0353e3_idx')],
            },
        ),
    ]
