# Generated by Django 5.1 on 2026-01-10 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_requests', '0002_initial'),
        ('school_requests', '0002_initial'),
        ('schools', '0001_initial'),
        ('warehouses', '0005_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryToProvinceShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, db_index=True, help_text='كود التتبع الفريد', max_length=50, null=True)),
                ('books', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'قيد الإنشاء'), ('assigned', 'مُسندة لمندوب'), ('out_for_delivery', 'خارجة للتسليم'), ('delivered', 'تم التسليم'), ('confirmed', 'مؤكدة (يتم خصم المخزون)'), ('canceled', 'ملغاة')], default='pending', max_length=20)),
                ('current_latitude', models.FloatField(blank=True, help_text='موقع المندوب الحالي - خط العرض', null=True)),
                ('current_longitude', models.FloatField(blank=True, help_text='موقع المندوب الحالي - خط الطول', null=True)),
                ('last_location_update', models.DateTimeField(blank=True, help_text='آخر تحديث للموقع', null=True)),
                ('proof_photo', models.ImageField(blank=True, help_text='صورة إثبات التسليم', null=True, upload_to='shipments/ministry/proof/')),
                ('digital_signature', models.ImageField(blank=True, help_text='التوقيع الرقمي', null=True, upload_to='shipments/ministry/signatures/')),
                ('recipient_name', models.CharField(blank=True, default='', help_text='اسم المستلم', max_length=255)),
                ('delivery_notes', models.TextField(blank=True, default='', help_text='ملاحظات التسليم')),
                ('delivery_condition', models.CharField(blank=True, default='good', help_text='good/damaged', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When province confirmed receipt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_delivery_at', models.DateTimeField(blank=True, help_text='وقت بدء التوصيل', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='وقت التسليم الفعلي', null=True)),
                ('qr_token', models.CharField(blank=True, help_text='رمز فريد للـ QR Code', max_length=64, null=True, unique=True)),
                ('qr_code_image', models.TextField(blank=True, help_text='صورة QR Code بصيغة base64', null=True)),
                ('qr_expires_at', models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية الـ QR Code', null=True)),
                ('qr_used', models.BooleanField(default=False, help_text='هل تم استخدام الـ QR Code للتأكيد')),
                ('qr_scanned_at', models.DateTimeField(blank=True, help_text='وقت مسح الـ QR Code', null=True)),
                ('assigned_courier', models.ForeignKey(blank=True, limit_choices_to={'role': 'ministry_driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_assigned_shipments', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Province staff who confirmed receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_confirmed_shipments', to=settings.AUTH_USER_MODEL)),
                ('from_ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_shipments_out', to='warehouses.ministrywarehouse')),
                ('related_request', models.ForeignKey(blank=True, help_text='Link to the originating book request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_shipments', to='book_requests.bookrequest')),
                ('to_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_shipments_in', to='warehouses.provincewarehouse')),
            ],
            options={
                'verbose_name': 'شحنة الوزارة للمحافظة',
                'verbose_name_plural': 'شحنات الوزارة للمحافظات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvinceToSchoolShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, db_index=True, help_text='كود التتبع الفريد', max_length=50, null=True)),
                ('books', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'قيد الإنشاء'), ('assigned', 'مُسندة لمندوب'), ('out_for_delivery', 'خارجة للتسليم'), ('delivered', 'تم التسليم'), ('confirmed', 'مؤكدة (يتم خصم المخزون)'), ('canceled', 'ملغاة')], default='pending', max_length=20)),
                ('current_latitude', models.FloatField(blank=True, help_text='موقع المندوب الحالي - خط العرض', null=True)),
                ('current_longitude', models.FloatField(blank=True, help_text='موقع المندوب الحالي - خط الطول', null=True)),
                ('last_location_update', models.DateTimeField(blank=True, help_text='آخر تحديث للموقع', null=True)),
                ('proof_photo', models.ImageField(blank=True, help_text='صورة إثبات التسليم', null=True, upload_to='shipments/province/proof/')),
                ('digital_signature', models.ImageField(blank=True, help_text='التوقيع الرقمي', null=True, upload_to='shipments/province/signatures/')),
                ('recipient_name', models.CharField(blank=True, default='', help_text='اسم المستلم', max_length=255)),
                ('delivery_notes', models.TextField(blank=True, default='', help_text='ملاحظات التسليم')),
                ('delivery_condition', models.CharField(blank=True, default='good', help_text='good/damaged', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When school confirmed receipt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_delivery_at', models.DateTimeField(blank=True, help_text='وقت بدء التوصيل', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='وقت التسليم الفعلي', null=True)),
                ('qr_token', models.CharField(blank=True, help_text='رمز فريد للـ QR Code', max_length=64, null=True, unique=True)),
                ('qr_code_image', models.TextField(blank=True, help_text='صورة QR Code بصيغة base64', null=True)),
                ('qr_expires_at', models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية الـ QR Code', null=True)),
                ('qr_used', models.BooleanField(default=False, help_text='هل تم استخدام الـ QR Code للتأكيد')),
                ('qr_scanned_at', models.DateTimeField(blank=True, help_text='وقت مسح الـ QR Code', null=True)),
                ('assigned_courier', models.ForeignKey(blank=True, limit_choices_to={'role': 'province_driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_assigned_shipments', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='School staff who confirmed receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_confirmed_shipments', to=settings.AUTH_USER_MODEL)),
                ('from_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_shipments_out', to='warehouses.provincewarehouse')),
                ('related_school_request', models.ForeignKey(blank=True, help_text='Link to the originating school request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_shipments', to='school_requests.schoolrequest')),
                ('to_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_shipments_in', to='schools.school')),
            ],
            options={
                'verbose_name': 'شحنة المحافظة للمدرسة',
                'verbose_name_plural': 'شحنات المحافظة للمدارس',
                'ordering': ['-created_at'],
            },
        ),
    ]
