# Generated by Django 5.1 on 2026-01-10 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_requests', '0002_initial'),
        ('school_requests', '0002_initial'),
        ('schools', '0001_initial'),
        ('warehouses', '0006_ministrytoprovinceshipment_provincetoschoolshipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, help_text='مندوب الوزارة المكلف بالتوصيل', limit_choices_to={'role': 'ministry_driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_assigned_shipments', to=settings.AUTH_USER_MODEL, verbose_name='المندوب المكلف'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='books',
            field=models.JSONField(verbose_name='الكتب'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ ووقت تأكيد المحافظة للاستلام', null=True, verbose_name='تاريخ التأكيد'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='موظف المحافظة الذي أكد الاستلام', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_confirmed_shipments', to=settings.AUTH_USER_MODEL, verbose_name='تم التأكيد بواسطة'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='current_latitude',
            field=models.FloatField(blank=True, help_text='موقع المندوب الحالي - خط العرض', null=True, verbose_name='خط العرض الحالي'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='current_longitude',
            field=models.FloatField(blank=True, help_text='موقع المندوب الحالي - خط الطول', null=True, verbose_name='خط الطول الحالي'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='التاريخ والوقت الفعلي للتسليم', null=True, verbose_name='وقت التسليم'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='delivery_condition',
            field=models.CharField(blank=True, default='good', help_text='حالة الشحنة عند التسليم (جيدة/تالفة)', max_length=20, verbose_name='حالة التسليم'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='delivery_notes',
            field=models.TextField(blank=True, default='', help_text='ملاحظات حول عملية التسليم', verbose_name='ملاحظات التسليم'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='digital_signature',
            field=models.ImageField(blank=True, help_text='التوقيع الرقمي للمستلم', null=True, upload_to='shipments/ministry/signatures/', verbose_name='التوقيع الرقمي'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='from_ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_shipments_out', to='warehouses.ministrywarehouse', verbose_name='من مخزن الوزارة'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='آخر تحديث لموقع المندوب', null=True, verbose_name='آخر تحديث للموقع'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='proof_photo',
            field=models.ImageField(blank=True, help_text='صورة تثبت استلام الشحنة', null=True, upload_to='shipments/ministry/proof/', verbose_name='صورة إثبات التسليم'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='qr_code_image',
            field=models.TextField(blank=True, help_text='صورة رمز الاستجابة السريع بصيغة base64', null=True, verbose_name='صورة رمز QR'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية رمز الاستجابة السريع', null=True, verbose_name='تاريخ انتهاء رمز QR'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='qr_scanned_at',
            field=models.DateTimeField(blank=True, help_text='التاريخ والوقت الذي تم فيه مسح رمز الاستجابة السريع', null=True, verbose_name='وقت مسح رمز QR'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='qr_token',
            field=models.CharField(blank=True, help_text='رمز فريد لرمز الاستجابة السريع', max_length=64, null=True, unique=True, verbose_name='رمز QR'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='qr_used',
            field=models.BooleanField(default=False, help_text='هل تم استخدام رمز الاستجابة السريع للتأكيد', verbose_name='تم استخدام رمز QR'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='recipient_name',
            field=models.CharField(blank=True, default='', help_text='اسم الشخص الذي استلم الشحنة', max_length=255, verbose_name='اسم المستلم'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='related_request',
            field=models.ForeignKey(blank=True, help_text='ربط بطلب الكتب الأصلي من المحافظة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_shipments', to='book_requests.bookrequest', verbose_name='الطلب المرتبط'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='started_delivery_at',
            field=models.DateTimeField(blank=True, help_text='التاريخ والوقت الذي بدأ فيه التوصيل', null=True, verbose_name='وقت بدء التوصيل'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الإنشاء'), ('assigned', 'مُسندة لمندوب'), ('out_for_delivery', 'خارجة للتسليم'), ('delivered', 'تم التسليم'), ('confirmed', 'مؤكدة (يتم خصم المخزون)'), ('canceled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='to_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_shipments_in', to='warehouses.provincewarehouse', verbose_name='إلى مخزن المحافظة'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, help_text='كود التتبع الفريد للشحنة', max_length=50, null=True, verbose_name='كود التتبع'),
        ),
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, help_text='مندوب المحافظة المكلف بالتوصيل', limit_choices_to={'role': 'province_driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_assigned_shipments', to=settings.AUTH_USER_MODEL, verbose_name='المندوب المكلف'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='books',
            field=models.JSONField(verbose_name='الكتب'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ ووقت تأكيد المدرسة للاستلام', null=True, verbose_name='تاريخ التأكيد'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='موظف المدرسة الذي أكد الاستلام', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_confirmed_shipments', to=settings.AUTH_USER_MODEL, verbose_name='تم التأكيد بواسطة'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='current_latitude',
            field=models.FloatField(blank=True, help_text='موقع المندوب الحالي - خط العرض', null=True, verbose_name='خط العرض الحالي'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='current_longitude',
            field=models.FloatField(blank=True, help_text='موقع المندوب الحالي - خط الطول', null=True, verbose_name='خط الطول الحالي'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='التاريخ والوقت الفعلي للتسليم', null=True, verbose_name='وقت التسليم'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='delivery_condition',
            field=models.CharField(blank=True, default='good', help_text='حالة الشحنة عند التسليم (جيدة/تالفة)', max_length=20, verbose_name='حالة التسليم'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='delivery_notes',
            field=models.TextField(blank=True, default='', help_text='ملاحظات حول عملية التسليم', verbose_name='ملاحظات التسليم'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='digital_signature',
            field=models.ImageField(blank=True, help_text='التوقيع الرقمي للمستلم', null=True, upload_to='shipments/province/signatures/', verbose_name='التوقيع الرقمي'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='from_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_shipments_out', to='warehouses.provincewarehouse', verbose_name='من مخزن المحافظة'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='آخر تحديث لموقع المندوب', null=True, verbose_name='آخر تحديث للموقع'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='proof_photo',
            field=models.ImageField(blank=True, help_text='صورة تثبت استلام الشحنة', null=True, upload_to='shipments/province/proof/', verbose_name='صورة إثبات التسليم'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='qr_code_image',
            field=models.TextField(blank=True, help_text='صورة رمز الاستجابة السريع بصيغة base64', null=True, verbose_name='صورة رمز QR'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية رمز الاستجابة السريع', null=True, verbose_name='تاريخ انتهاء رمز QR'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='qr_scanned_at',
            field=models.DateTimeField(blank=True, help_text='التاريخ والوقت الذي تم فيه مسح رمز الاستجابة السريع', null=True, verbose_name='وقت مسح رمز QR'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='qr_token',
            field=models.CharField(blank=True, help_text='رمز فريد لرمز الاستجابة السريع', max_length=64, null=True, unique=True, verbose_name='رمز QR'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='qr_used',
            field=models.BooleanField(default=False, help_text='هل تم استخدام رمز الاستجابة السريع للتأكيد', verbose_name='تم استخدام رمز QR'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='recipient_name',
            field=models.CharField(blank=True, default='', help_text='اسم الشخص الذي استلم الشحنة', max_length=255, verbose_name='اسم المستلم'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='related_school_request',
            field=models.ForeignKey(blank=True, help_text='ربط بطلب الكتب الأصلي من المدرسة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_shipments', to='school_requests.schoolrequest', verbose_name='الطلب المرتبط'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='started_delivery_at',
            field=models.DateTimeField(blank=True, help_text='التاريخ والوقت الذي بدأ فيه التوصيل', null=True, verbose_name='وقت بدء التوصيل'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الإنشاء'), ('assigned', 'مُسندة لمندوب'), ('out_for_delivery', 'خارجة للتسليم'), ('delivered', 'تم التسليم'), ('confirmed', 'مؤكدة (يتم خصم المخزون)'), ('canceled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='to_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_shipments_in', to='schools.school', verbose_name='إلى المدرسة'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, help_text='كود التتبع الفريد للشحنة', max_length=50, null=True, verbose_name='كود التتبع'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
