# Generated by Django 5.1 on 2026-01-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0007_alter_ministrytoprovinceshipment_assigned_courier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='shipment',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
