# Generated by Django 5.1 on 2026-01-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0008_remove_shipment_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministrywarehouse',
            options={'verbose_name': 'مستودع الوزارة', 'verbose_name_plural': 'مستودعات الوزارة'},
        ),
        migrations.AlterModelOptions(
            name='provincewarehouse',
            options={'verbose_name': 'مستودع المحافظة', 'verbose_name_plural': 'مستودعات المحافظات'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'حركة المخزون', 'verbose_name_plural': 'حركات المخزون'},
        ),
        migrations.AlterModelOptions(
            name='warehousestock',
            options={'verbose_name': 'مخزون المستودع', 'verbose_name_plural': 'مخزون المستودعات'},
        ),
    ]
