# Generated by Django 5.1 on 2026-01-14 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0010_alter_ministrytoprovinceshipment_assigned_courier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministrytoprovinceshipment',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, help_text='مندوب الوزارة المكلف بالتوصيل', limit_choices_to={'role__in': ['ministry_courier', 'ministry_driver']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministry_assigned_shipments', to=settings.AUTH_USER_MODEL, verbose_name='المندوب المكلف'),
        ),
        migrations.AlterField(
            model_name='provincetoschoolshipment',
            name='assigned_courier',
            field=models.ForeignKey(blank=True, help_text='مندوب المحافظة المكلف بالتوصيل', limit_choices_to={'role__in': ['province_courier', 'province_driver']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province_assigned_shipments', to=settings.AUTH_USER_MODEL, verbose_name='المندوب المكلف'),
        ),
    ]
