# Generated by Django 5.1 on 2025-11-10 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('arabic', 'اللغة العربية'), ('math', 'الرياضيات'), ('science', 'العلوم'), ('english', 'اللغة الإنجليزية'), ('islamic', 'التربية الإسلامية'), ('social', 'التربية الاجتماعية')], max_length=50, verbose_name='المادة')),
                ('grade_level', models.CharField(choices=[('1', 'الصف الأول'), ('2', 'الصف الثاني'), ('3', 'الصف الثالث'), ('4', 'الصف الرابع'), ('5', 'الصف الخامس'), ('6', 'الصف السادس')], max_length=5, verbose_name='الصف الدراسي')),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'الفصل الأول'), (2, 'الفصل الثاني')], default=1, verbose_name='الفصل الدراسي')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='رقم الطبعة')),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='سنة النشر')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='إجمالي المخزون')),
            ],
            options={
                'ordering': ['grade_level', 'subject', 'term'],
                'indexes': [models.Index(fields=['subject'], name='books_book_subject_69111d_idx'), models.Index(fields=['grade_level'], name='books_book_grade_l_67dccf_idx'), models.Index(fields=['term'], name='books_book_term_a6b29b_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject', 'grade_level', 'term', 'edition', 'year'), name='uniq_book_subject_grade_term_edition_year')],
            },
        ),
    ]
