# Generated by Django 5.1 on 2025-11-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('total_quantity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx'), models.Index(fields=['title'], name='books_book_title_d3218d_idx')],
            },
        ),
    ]
