# Generated by Django 5.1 on 2025-12-23 18:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الصف')),
                ('level', models.CharField(choices=[('primary', 'ابتدائي'), ('middle', 'أساسي'), ('secondary', 'ثانوي')], max_length=20, verbose_name='المرحلة التعليمية')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتيب الصف من الأصغر للأكبر', verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المادة')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز المادة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المادة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'المواد الدراسية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الفصل')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='رقم الفصل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_subjects', to='books.grade', verbose_name='الصف')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_grades', to='books.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'مادة مسموحة للصف',
                'verbose_name_plural': 'المواد المسموحة للصفوف',
                'ordering': ['grade__order', 'subject__name'],
                'unique_together': {('grade', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='رقم الطبعة')),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='سنة النشر')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='إجمالي المخزون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.grade', verbose_name='الصف الدراسي')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.subject', verbose_name='المادة')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.term', verbose_name='الفصل الدراسي')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'الكتب',
                'ordering': ['grade__order', 'subject__name', 'term__number'],
                'indexes': [models.Index(fields=['subject', 'grade', 'term'], name='books_book_subject_f70fea_idx'), models.Index(fields=['year'], name='books_book_year_d303c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject', 'grade', 'term', 'edition', 'year'), name='uniq_book_subject_grade_term_edition_year')],
            },
        ),
    ]
