# Generated by Django 5.1 on 2025-11-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='grade_level',
            field=models.CharField(choices=[('1', 'الأول'), ('2', 'الثاني'), ('3', 'الثالث'), ('4', 'الرابع'), ('5', 'الخامس'), ('6', 'السادس'), ('7', 'السابع'), ('8', 'الثامن'), ('9', 'التاسع'), ('10', 'الأول الثانوي'), ('11', 'الثاني الثانوي'), ('12', 'الثالث الثانوي')], max_length=5, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(choices=[('arabic', 'اللغة العربية'), ('math', 'الرياضيات'), ('science', 'العلوم'), ('english', 'اللغة الإنجليزية'), ('islamic', 'التربية الإسلامية'), ('social', 'التربية الاجتماعية'), ('history', 'التاريخ'), ('geography', 'الجغرافيا'), ('quran', 'القرآن الكريم'), ('art', 'التربية الفنية'), ('music', 'التربية الموسيقية'), ('sports', 'التربية الرياضية'), ('computer', 'الحاسوب'), ('handcraft', 'الأشغال اليدوية'), ('physics', 'الفيزياء'), ('chemistry', 'الكيمياء'), ('biology', 'الأحياء'), ('advanced_math', 'الرياضيات المتقدمة'), ('philosophy', 'الفلسفة والمنطق'), ('psychology', 'علم النفس'), ('sociology', 'علم الاجتماع'), ('arabic_literature', 'الأدب العربي'), ('economics', 'الاقتصاد')], max_length=50, verbose_name='المادة'),
        ),
    ]
