# Generated by Django 5.1 on 2025-11-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['grade_level', 'subject']},
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_isbn_54becd_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_title_d3218d_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الطبعة'),
        ),
        migrations.AddField(
            model_name='book',
            name='grade_level',
            field=models.CharField(choices=[('1', 'الصف الأول'), ('2', 'الصف الثاني'), ('3', 'الصف الثالث'), ('4', 'الصف الرابع'), ('5', 'الصف الخامس'), ('6', 'الصف السادس')], default=5, max_length=5, verbose_name='الصف الدراسي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.CharField(choices=[('arabic', 'اللغة العربية'), ('math', 'الرياضيات'), ('science', 'العلوم'), ('english', 'اللغة الإنجليزية'), ('islamic', 'التربية الإسلامية'), ('social', 'التربية الاجتماعية')], default='1', max_length=50, verbose_name='المادة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة النشر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='إجمالي المخزون'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['subject'], name='books_book_subject_69111d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['grade_level'], name='books_book_grade_l_67dccf_idx'),
        ),
    ]
