# Generated by Django 5.1 on 2025-11-05 21:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مرسل للمحافظة'), ('approved', 'مقبول من المحافظة'), ('rejected', 'مرفوض من المحافظة'), ('fulfilled', 'تمّ التوريد للمدرسة'), ('cancelled', 'ملغى من المدرسة')], default='draft', max_length=20)),
                ('reason_rejected', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'school_user'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'province_staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_requests', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_request_items', to='books.book')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='school_requests.schoolrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='schoolrequest',
            index=models.Index(fields=['status'], name='school_requ_status_fdea9e_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrequest',
            index=models.Index(fields=['-created_at'], name='school_requ_created_aa3b34_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrequest',
            index=models.Index(fields=['school'], name='school_requ_school__dfeb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrequestitem',
            index=models.Index(fields=['request'], name='school_requ_request_f91a45_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrequestitem',
            index=models.Index(fields=['book'], name='school_requ_book_id_e31ce9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolrequestitem',
            unique_together={('request', 'book')},
        ),
    ]
