# Generated by Django 5.1 on 2025-11-10 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('school_requests', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolrequest',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['province_driver']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['province_staff', 'province_warehouse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_requests_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolrequest',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_requests', to='schools.school'),
        ),
        migrations.AddField(
            model_name='schoolrequestitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_request_items', to='books.book'),
        ),
        migrations.AddField(
            model_name='schoolrequestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='school_requests.schoolrequest'),
        ),
        migrations.AddIndex(
            model_name='schoolrequest',
            index=models.Index(fields=['status'], name='school_requ_status_fdea9e_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrequest',
            index=models.Index(fields=['-created_at'], name='school_requ_created_aa3b34_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrequest',
            index=models.Index(fields=['school'], name='school_requ_school__dfeb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrequestitem',
            index=models.Index(fields=['request'], name='school_requ_request_f91a45_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolrequestitem',
            index=models.Index(fields=['book'], name='school_requ_book_id_e31ce9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolrequestitem',
            unique_together={('request', 'book')},
        ),
    ]
