# Generated by Django 5.1 on 2025-12-23 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('ministry_admin', 'مديرالوزارة'), ('ministry_staff', 'موظف الوزارة'), ('ministry_warehouse', 'موظف مخازن الوزارة'), ('ministry_driver', 'مندوب توصيل الوزارة'), ('province_admin', 'مدير المحافظة'), ('province_staff', 'موظف المحافظة'), ('province_warehouse', 'موظف مخازن المحافظة'), ('province_driver', 'مندوب توصيل المحافظة'), ('school_staff', 'موظف المدرسة')], max_length=30)),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('school', models.ForeignKey(blank=True, help_text='المدرسة المرتبط بها المستخدم (تستخدم غالباً مع موظف المدرسة).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='schools.school', verbose_name='المدرسة')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
