# Generated by Django 5.1 on 2025-11-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='المدرسة المرتبط بها المستخدم (تستخدم غالباً مع موظف المدرسة).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='schools.school', verbose_name='المدرسة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ministry_staff', 'موظف الوزارة'), ('ministry_warehouse', 'موظف مخازن الوزارة'), ('ministry_driver', 'مندوب توصيل الوزارة'), ('province_staff', 'موظف المحافظة'), ('province_warehouse', 'موظف مخازن المحافظة'), ('province_driver', 'مندوب توصيل المحافظة'), ('school_staff', 'موظف المدرسة')], max_length=30),
        ),
    ]
