# Generated by Django 5.1 on 2025-11-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_school_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ministry_staff', 'موظف الوزارة'), ('ministry_warehouse', 'موظف مخازن الوزارة'), ('ministry_driver', 'مندوب توصيل الوزارة'), ('province_admin', 'مدير المحافظة'), ('province_staff', 'موظف المحافظة'), ('province_warehouse', 'موظف مخازن المحافظة'), ('province_driver', 'مندوب توصيل المحافظة'), ('school_staff', 'موظف المدرسة')], max_length=30),
        ),
    ]
